source: ./src
destination: ./.grunt/build

exclude: ["bower_components"]

#Outputting
permalink: pretty

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
